blank_issues_enabled: false
contact_links:
  - name: Questions / General Discussion
    url: https://github.com/pymcu/.github/issues/new
    about: Open an issue with the "Question" label if you need help or have general feedback.
